spring:
  application:
    name: ecms
  data:
   redis:
    host: 127.0.0.1
    port: 6379
   # dev profile active by default

grpc:
  server:
    port: 9090
    reflection-service-enabled: true

#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: myStrongPassword

