spring:
  application:
    name: ecms
  main:
    allow-bean-definition-overriding: true
   # dev profile active by default

grpc:
  server:
    port: 9090
    reflection-service-enabled: true

# Uncomment and configure Redis if needed
# redis:
#   host: localhost
#   port: 6379
