spring:
  application:
    name: ecms
  main:
    allow-bean-definition-overriding: true		   
   # dev profile active by default
  data:
    redis:
      host: 127.0.0.1
      port: 6379
grpc:
  server:
    port: 9090
    reflection-service-enabled: true

# Uncomment and configure Redis if needed
 
cache:
  auth:
    usernamepasswordauth:
      username: admin
      password: secret123
logging:
  file:
    name: logs/ecms.log	 
  level:
    root: INFO
    '[com.sidecar.ecms]': DEBUG 